# Generated by Django 5.1.4 on 2024-12-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type_commande', models.CharField(choices=[('ACHAT', 'Commande fournisseur'), ('VENTE', 'Commande client')], default='VENTE', max_length=10)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('EN_COURS_LIVRAISON', 'En cours de livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('conditions_paiement', models.TextField(blank=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=50)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
                ('modifiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_modifiees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Sama_Stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('code_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('emplacement', models.CharField(blank=True, max_length=100)),
                ('unite_mesure', models.CharField(default='unité', max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sama_Stock.categorie')),
                ('fournisseur_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sama_Stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock')], max_length=6)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sama_Stock.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField()),
                ('quantite_reelle', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sama_Stock.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sama_Stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sama_Stock.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sama_Stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
